version: '3'
services:
  mongodb:
    container_name: "mongodb"
    image: "mongo:latest"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
